/* 
 * This file has been automatically generated by the jrl-cmakemodules.
 * Please see https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/config.hh.cmake for details.
*/

#ifndef TSID_CONFIG_HH
# define TSID_CONFIG_HH

// Package version (header).
# define TSID_VERSION_UNKNOWN_TAG 0 // Used to mention that the current version is unknown.
# define TSID_VERSION "1.4.1"
# define TSID_MAJOR_VERSION 1
# define TSID_MINOR_VERSION 4
# define TSID_PATCH_VERSION 1

#define TSID_VERSION_AT_LEAST(major, minor, patch) (TSID_MAJOR_VERSION>major || (TSID_MAJOR_VERSION>=major && \
                                                             (TSID_MINOR_VERSION>minor || (TSID_MINOR_VERSION>=minor && \
                                                                                                     TSID_PATCH_VERSION>=patch))))

#define TSID_VERSION_AT_MOST(major, minor, patch) (TSID_MAJOR_VERSION<major || (TSID_MAJOR_VERSION<=major && \
                                                            (TSID_MINOR_VERSION<minor || (TSID_MINOR_VERSION<=minor && \
                                                                                                     TSID_PATCH_VERSION<=patch))))

// Handle portable symbol export.
// Defining manually which symbol should be exported is required
// under Windows whether MinGW or MSVC is used.
//
// The headers then have to be able to work in two different modes:
// - dllexport when one is building the library,
// - dllimport for clients using the library.
//
// On Linux, set the visibility accordingly. If C++ symbol visibility
// is handled by the compiler, see: http://gcc.gnu.org/wiki/Visibility
# if defined _WIN32 || defined __CYGWIN__
// On Microsoft Windows, use dllimport and dllexport to tag symbols.
#  define TSID_DLLIMPORT __declspec(dllimport)
#  define TSID_DLLEXPORT __declspec(dllexport)
#  define TSID_DLLLOCAL
# else
// On Linux, for GCC >= 4, tag symbols using GCC extension.
#  if __GNUC__ >= 4
#   define TSID_DLLIMPORT __attribute__ ((visibility("default")))
#   define TSID_DLLEXPORT __attribute__ ((visibility("default")))
#   define TSID_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
// Otherwise (GCC < 4 or another compiler is used), export everything.
#   define TSID_DLLIMPORT
#   define TSID_DLLEXPORT
#   define TSID_DLLLOCAL
#  endif // __GNUC__ >= 4
# endif // defined _WIN32 || defined __CYGWIN__

# ifdef TSID_STATIC
// If one is using the library statically, get rid of
// extra information.
#  define TSID_DLLAPI
#  define TSID_LOCAL
# else
// Depending on whether one is building or using the
// library define DLLAPI to import or export.
#  ifdef tsid_EXPORTS
#   define TSID_DLLAPI TSID_DLLEXPORT
#  else
#   define TSID_DLLAPI TSID_DLLIMPORT
#  endif // TSID_EXPORTS
#  define TSID_LOCAL TSID_DLLLOCAL
# endif // TSID_STATIC
#endif //! TSID_CONFIG_HH
